
###
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "Blog title",
  "author": "Blog author",
  "content": "Blog content content content"
}

###

GET http://localhost:8080/posts/all?page=0&size=5
Content-Type: application/json

###

GET http://localhost:8080/posts?id=49937336-d60d-43f4-87f3-1e3c2e481d35
Content-Type: application/json

###

PUT http://localhost:8080/posts
Content-Type: application/json

{
  "id": "49937336-d60d-43f4-87f3-1e3c2e481d35",
  "title": "Blog title2",
  "author": "Blog author2",
  "content": "Blog content content content2"
}

###
DELETE http://localhost:8080/posts?id=6d20717a-71bd-4132-8709-2c3ba203afef
Content-Type: application/json

###

