spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///dados/wks/spring/udemy/spring-cloud/git-localconfig-repo
  #       native:
  #         search-locations: file:///dados/wks/spring/udemy/spring-cloud/dirprops
  # profiles:
  #   active: native
server:
  port: 8888

# spring.application.name=spring-cloud-config-server
# server.port=8888
# spring.cloud.config.server.git.uri=file:///dados/wks/spring/udemy/spring-cloud/git-localconfig-repo

# https://github.com/rashidi/jdbc-env-repo-sample

# Para acessar as propriedades: http://localhost:8888/limits-service/default
# [branch master] --> http://localhost:8888/limits-service/qa/master (or without last word)
# [branch br1]    --> http://localhost:8888/limits-service/qa/br1
